---
env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:react/recommended
  - standard
  - semistandard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  impliedStrict: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {}
settings:
  react:
    version: detect
  linkComponents:
    - name: Link
      linkAttribute: to
